# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], default='text', max_length=255)),
                ('allow_additional_options', models.BooleanField(default=False)),
                ('default_value', models.CharField(max_length=255, null=True)),
                ('read_only', models.BooleanField(default=False)),
            ],
        ),
    ]
