# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], default='text', max_length=255)),
                ('allow_additional_options', models.BooleanField(default=False)),
                ('default_value', models.CharField(max_length=255, null=True)),
                ('read_only', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=True)),
                ('min', models.TextField(blank=True, default=None, null=True)),
                ('max', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='fields.Field')),
            ],
        ),
    ]
