# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('boolean', 'boolean')], default='text', max_length=255),
        ),
    ]
