# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:29
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_field_validation_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='validation_json',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
