# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_auto_20160701_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='validation_json',
        ),
        migrations.AddField(
            model_name='field',
            name='high',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='low',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
